### ISSUE TITLE
Complex structure validation

### ISSUE THREAD

**Issue by ooflorent** [thejameskyle/revalid#2]
`revalid` looks interesting. However it would be awesome if it could possible to validate complex object structures.

**Conditional validation**

Reads a field value and runs the correct validator.

```js
// function condition(hashFn, mappings);
condition(value => value.type, {
  foo: fooValidator,
  bar: barValidator,
})
```

**Lists**

Validates every items of an array-list structure.

```js
// function list(validator)
const phonesValidator = list(phoneValidator)
```

**Comment by thejameskyle** [comment]
The built in validators should not be looking into the object structure of the values that are passed to it. You can define your own validators that do exactly that though just as long as you follow the interface that revalid defines.

Revalid is not going to be built to support every possible use case, it's meant to define a simplistic interface that you can build on top of.
